// frontend/src/main.js
import { createApp } from 'vue'
import App from './App.vue'
// import router from './router' // Uncomment if using Vue Router
// import store from './store'   // Uncomment if using Pinia/Vuex
import './assets/tailwind.css'; // Import Tailwind's base styles (will be generated by Tailwind CLI)

const app = createApp(App)

// app.use(router) // Uncomment if using Vue Router
// app.use(store)  // Uncomment if using Pinia/Vuex

app.mount('#app')
